[package]
name = "graphplay2"
version = "0.1.0"
authors = ["Andrew Watts <ahwatts@gmail.com>"]

[[bin]]
name = "graphplay2"

[dependencies]
byteorder = "^0.5.1"
glium = "^0.14.0"
nalgebra = "^0.8.1"
num = "^0.1.32"
