[package]
name = "graphplay2"
version = "0.1.0"
authors = ["Andrew Watts <ahwatts@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "^1.4.2"
glium = "^0.29.0"
nalgebra = "^0.24.1"
num = "^0.3.1"
